####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 244
  unit_system: imperial
  time_zone: !secret time_zone
  whitelist_external_dirs:
    - /config
    - /share

####################################################
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
cloud: !include cloud.yaml
frontend: !include frontend.yaml
ios: !include ios.yaml
media_player: !include media_player.yaml
notify: !include notification.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://www.home-assistant.io/components/climate/
climate:
  - platform: zwave

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/components/system_health/
system_health:

#https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate

####################################################
#               BINARY SENSOR                      #
####################################################

#https://home-assistant.io/components/binary_sensor.ping/
binary_sensor:
  - platform: ping
    host: 192.168.100.1
    name: Modem

####################################################
#                     COVER                        #
####################################################
#https://www.home-assistant.io/components/opengarage/
cover:
  platform: opengarage
  covers:
      garage:
        host:  192.168.1.18
        device_key: !secret device_key
        name: Garage Door

####################################################
#                    GROUP                         #
####################################################

#https://www.home-assistant.io/components/group/
group:
  outside_lights:
    - light.yeelight1
    - light.yeelight2
    - light.yeelight3
    - light.yeelight4
  front_lights:
    - light.yeelight1
    - light.yeelight3
    - light.yeelight4
  adam_home_presence:
    - device_tracker.adam_s_iphone_2 #GPS
    - device_tracker.adam_s_iphone #WiFi
  amy_home_presence:
    - device_tracker.amy_s_iphone_2 #GPS
    - device_tracker.amy_s_iphone #WiFi
  home_presence:
    - device_tracker.adam_s_iphone_2 #GPS
    - device_tracker.adam_s_iphone #WiFi
    - device_tracker.amy_s_iphone2 #GPS
    - device_tracker.amy_s_iphone #WiFi
  living_room_lamps:
    - switch.basic1
    - light.yeelightrgb2

####################################################
#                 INPUT BOOLEAN                    #
####################################################

#https://home-assistant.io/components/input_boolean/
input_boolean:
  vacation:
    name: Vacation Mode
    initial: off
  guest:
    name: Guest Mode
    initial: off
  feeddog:
    name: feeddog
    initial: off
  doorbelllight:
    name: doorbelllight
    initial: off

####################################################
#                    INPUT SELECT                  #
####################################################

#https://home-assistant.io/components/input_select/
input_select:
  notification_bulb2_color:
    options:
      - "Normal"
      - "White"
      - "Red"
      - "Orange"
      - "Yellow"
      - "Green"
      - "Blue"
      - "Indigo"
      - "Violet"
      - "Purple"
    icon: mdi:lightbulb
    initial: White

####################################################
#                     LIGHT                        #
####################################################

#https://www.home-assistant.io/components/light.group/
light:
  - platform: group
    name: Front Lights
    entities:
      - light.yeelight1
      - light.yeelight3
      - light.yeelight4

  - platform: group
    name: Bedroom Lights
    entities:
      - light.tradfri_bulb_e26_ws_opal_980lm_2_2
      - light.tradfri_bulb_e26_ws_opal_980lm_3

####################################################
#                   SPEETEST                       #
####################################################

#https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 1776
  monitored_conditions:
    - download
    - upload

####################################################
#                TRADFRI HUB                       #
####################################################

#https://home-assistant.io/components/tradfri/
tradfri:
  host: 192.168.1.20
  allow_tradfri_groups: false

####################################################
#                   WEATHER                        #
####################################################

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

####################################################
#                     YEELIGHTS                    #
####################################################

#https://home-assistant.io/components/light.yeelight/
yeelight:
  devices:
    192.168.1.10:
      name: Yeelight1
    192.168.1.11:
      name: Yeelight2
    192.168.1.12:
      name: Yeelight3
    192.168.1.26:
      name: Yeelight4
    192.168.1.28:
      name: Yeelight5
    192.168.1.25:
      name: YeelightRGB2

####################################################
#                                                  #
#            END OF CONFIGURATION FILE             #
#                                                  #
####################################################
