
#########################################################
#                                                       #
#        INTERIOR GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Interior Garage Door Opened When Away"
    initial_state: true
    trigger:
      platform: state
      entity_id: sensor.gehingepinsensor2
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('person.adam') != 'home' }}"
        - condition: template
          value_template: "{{ states('person.amy') != 'home' }}"
    action:
      - service: notify.mobile_app_adams_iphone
        data:
          title: "Interior Garage Door Opened"
          message: "The Interior Garage Door was opened and Amy and Adam are not home"
      - service: notify.mobile_app_amy_s_iphone
        data:
          title: "Interior Garage Door Opened"
          message: "The Interior Garage Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#        Exterior GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Exterior Garage Door Opened When Away"
    initial_state: true    
    trigger:
      platform: state
      entity_id: cover.garagedoor
      to: 'open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('person.adam') != 'home' }}"
        - condition: template
          value_template: "{{ states('person.amy') != 'home' }}"
    action:
      - service: notify.mobile_app_adams_iphone
        data:
          title: "Exterior Garage Door Opened"
          message: "The Exterior Garage Door was opened and Amy and Adam are not home"
      - service: notify.mobile_app_amy_s_iphone
        data:
          title: "Exterior Garage Door Opened"
          message: "The Exterior Garage Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#              FRONT DOOR OPENED AND AWAY               #
#                                                       #
#########################################################

  - alias: "Front Door Opened When Away"
    initial_state: true
    trigger:
      platform: state
      entity_id: sensor.gehingepinsensor1
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('person.adam') != 'home' }}"
        - condition: template
          value_template: "{{ states('person.amy') != 'home' }}"
    action:
      - service: notify.mobile_app_adams_iphone
        data:
          title: "Front Door Opened"
          message: "The Front Door was opened and Amy and Adam are not home"
      - service: notify.mobile_app_amy_s_iphone
        data:
          title: "Front Door Opened"
          message: "The Front Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#        Exterior GARAGE DOOR OPENED AND AWAY           #
#                                                       #
#########################################################

  - alias: "Exterior Garage Door Left Open When Away"
    initial_state: true
    trigger:
      - platform: state
        entity_id: person.adam
      - platform: state
        entity_id: person.amy
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('person.adam') != 'home' }}"
        - condition: template
          value_template: "{{ states('person.amy') != 'home' }}"
        - condition: state
          entity_id: cover.garage_door
          state: 'open'
    action:
      - service: notify.mobile_app_adams_iphone
        data:
          title: "Exterior Garage Door Left Open"
          message: "The Exterior Garage Door was left open and Amy and Adam are not home"
      - service: notify.mobile_app_amy_s_iphone
        data:
          title: "Exterior Garage Door Left Open"
          message: "The Exterior Garage Door was left open and Amy and Adam are not home"

#########################################################
#                                                       #
#              BACK DOOR OPENED AND AWAY                #
#                                                       #
#########################################################

  - alias: "Back Door Opened When Away"
    initial_state: true
    trigger:
      platform: state
      entity_id: sensor.backdoorstatus
      to: 'Open'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('person.adam') != 'home' }}"
        - condition: template
          value_template: "{{ states('person.amy') != 'home' }}"
    action:
      - service: notify.mobile_app_adams_iphone
        data:
          title: "Back Door Opened"
          message: "The Back Door was opened and Amy and Adam are not home"
      - service: notify.mobile_app_amy_s_iphone
        data:
          title: "Back Door Opened"
          message: "The Back Door was opened and Amy and Adam are not home"

#########################################################
#                                                       #
#               DOORBELL PESSED NOTIFICATION            #
#                                                       #
#########################################################

  - alias: "Doorbell Pressed"
    initial_state: true  
    trigger:
      platform: state
      entity_id: sensor.doorbell
    condition:
      - condition: template
        value_template: "{{trigger.from_state.state != trigger.to_state.state}}"
      - condition: template
        value_template: "{{ states('person.adam') != 'away' }}"
      - condition: template
        value_template: "{{ states('person.amy') != 'away' }}"
      - condition: template
        value_template: "{{ states('input_boolean.guest_mode') != 'off' }}"
    action:
      - service: notify.fire_tv
        data:
          message: 'Somone Is At The Front Door'
          title: 'Doorbell'
          data:
            fontsize: max
            position: center
      - service: tts.google_translate_say
        entity_id: media_player.family_room_display
        data:
          message: 'Someone is at the front door!'
      - service: notify.mobile_app_adams_iphone
        data:
          title: "Doorbell Pressed"
          message: "The doorbell was pressed"
      - service: notify.mobile_app_amy_s_iphone
        data:
          title: "Doorbell Pressed"
          message: "The doorbell was pressed"
      - service_template: >-
          {%- if is_state('light.yeelightrgb2' , 'off') -%}
            input_boolean.turn_off
          {%- else -%}
            input_boolean.turn_on
          {%- endif -%}
        entity_id: input_boolean.doorbelllight
      - service: light.turn_on
        entity_id: light.yeelightrgb2
        data:
          effect: 'Strobe color'
      - delay: '00:00:02'
      - service: light.turn_on
        entity_id: light.yeelightrgb2
        data:
          effect: Stop
      - service_template: >-
          {%- if is_state('input_boolean.doorbelllight' , 'off') -%}
            light.turn_off
          {%- else -%}
            light.turn_on
          {%- endif -%}
        entity_id: light.yeelightrgb2
      - delay: 00:00:01
      - service: media_player.turn_off
        entity_id: media_player.family_room_display
      - delay: 00:00:01
      - service: switch.turn_on
        entity_id: switch.cast
      - delay: 00:00:30
      - service: switch.turn_on
        entity_id: switch.cast

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
